version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dmuser
      POSTGRES_PASSWORD: dmpass
      POSTGRES_DB: dmetro
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.v1
    image: dm-api:v1
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://dmuser:dmpass@db:5432/dmetro
    ports:
      - "5000:5000"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  db-data:
